name:                hs-qr-cable
version:             0.1.0.0
github:              "horus/hs-qr-cable"
license:             PublicDomain
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/horus/hs-qr-cable#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- binary
- bytestring
- case-insensitive
- cborg
- cryptonite
- http-client
- http-client-tls
- memory
- network
- pretty-simple
- serialise
- websockets

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hs-qr-cable-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    dependencies:
    - hs-qr-cable

tests:
  hs-qr-cable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    dependencies:
    - hs-qr-cable
